import Config

# API Keys configuration - loaded from environment variables
public_base_url = System.get_env("PUBLIC_BASE_URL") || "https://mds.ngrok.dev"
replicate_webhook_url = System.get_env("REPLICATE_WEBHOOK_URL")

audio_sync_mode =
  case String.downcase(System.get_env("AUDIO_SYNC_MODE") || "trim") do
    "stretch" -> :stretch
    "compress" -> :compress
    _ -> :trim
  end

audio_error_strategy =
  case String.downcase(System.get_env("AUDIO_ERROR_STRATEGY") || "continue_with_silence") do
    "halt" -> :halt
    _ -> :continue_with_silence
  end

replicate_max_concurrency =
  case System.get_env("REPLICATE_MAX_CONCURRENCY") do
    nil ->
      4

    value ->
      case Integer.parse(value) do
        {parsed, _} when parsed > 0 -> parsed
        _ -> 4
      end
  end

replicate_start_delay_ms =
  case System.get_env("REPLICATE_START_DELAY_MS") do
    nil ->
      1_000

    value ->
      case Integer.parse(value) do
        {parsed, _} when parsed >= 0 -> parsed
        _ -> 1_000
      end
  end

config :backend,
  replicate_api_key: System.get_env("REPLICATE_API_KEY"),
  xai_api_key: System.get_env("XAI_API_KEY"),
  elevenlabs_api_key: System.get_env("ELEVENLABS_API_KEY"),
  public_base_url: public_base_url,
  asset_base_url: public_base_url,
  replicate_webhook_url: replicate_webhook_url,
  video_generation_model: System.get_env("VIDEO_GENERATION_MODEL", "veo3"),
  auto_generate_audio: System.get_env("AUTO_GENERATE_AUDIO", "false") == "true",
  audio_merge_with_video: System.get_env("AUDIO_MERGE_WITH_VIDEO", "true") != "false",
  audio_fail_on_error: System.get_env("AUDIO_FAIL_ON_ERROR", "false") == "true",
  audio_sync_mode: audio_sync_mode,
  audio_error_strategy: audio_error_strategy,
  replicate_max_concurrency: replicate_max_concurrency,
  replicate_start_delay_ms: replicate_start_delay_ms

# Configure your database
config :backend, Backend.Repo,
  database: System.get_env("DATABASE_PATH", "data/backend_dev.db"),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  journal_mode: :wal

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :backend, BackendWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "tkntgyjvuEeos8yzuu7Tue2Dv/BJ2kBSpzRR0IHGavYYDJT1seuzNhMtrG3rAM5b",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :backend, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
